### ISSUE TITLE
I would like to ask you to add tags support to the automatic builds

### ISSUE THREAD

**Issue by EvilFreelancer** [bhigginsuk/discord-role-assigner#10]
Hello!

Thanks for your wonderful chat bot, it really helped me out, but I would like to have support for isolation by docker images tags, in case an unstable update is released (plus, your repository already has tags).

The image below will be an example of how this can be configured, it is very simple.

![Screenshot_20200103_003733](https://user-images.githubusercontent.com/9089568/71694969-cf6a2700-2dc1-11ea-8093-cffbbfbd3c9b.jpg)

Best regards, Paul.

**Comment by benji7425** [comment]
Hey, thanks for the suggestion! Currently my images are actually generated as part of my CI pipeline, run using Buildkite (you can view it [here](https://buildkite.com/benji7425/role-assigner) if you are interested).

I would need to update my [publish pipeline configuration](https://github.com/benji7425/discord-role-assigner/blob/master/.buildkite/pipeline.publish.yml#L9) to attach a tag before pushing, which I'm sure I can do in future. I am not actively developing this project at the moment, so will leave this issue open as a reminder for the future.

For now I have manually added tags for the latest versions to [my repositories](https://hub.docker.com/u/benji7425), hope that helps :)

**Comment by bhigginsuk** [comment]
Closing this as I am no longer actively maintaining this project, so it won't be an issue in future. Existing tags remain.
